'metadata'
Traceback (most recent call last):
  File "/home/runner/work/semgrep/semgrep/semgrep/semgrep/commands/wrapper.py", line 39, in wrapper
    func(*args, **kwargs)
  File "/home/runner/work/semgrep/semgrep/semgrep/semgrep/commands/scan.py", line 881, in scan
    ) = semgrep.semgrep_main.main(
  File "/home/runner/work/semgrep/semgrep/semgrep/semgrep/semgrep_main.py", line 273, in main
    all_rules = configs_obj.get_rules(no_rewrite_rule_ids)
  File "/home/runner/work/semgrep/semgrep/semgrep/semgrep/config_resolver.py", line 287, in get_rules
    OrderedDict(
  File "/home/runner/work/semgrep/semgrep/semgrep/semgrep/config_resolver.py", line 288, in <genexpr>
    (rule_without_metadata(rule), rule)
  File "/home/runner/work/semgrep/semgrep/semgrep/semgrep/rule.py", line 251, in rule_without_metadata
    del new_rule._raw["metadata"]
KeyError: 'metadata'
Not sending pseudonymous metrics since metrics are configured to AUTO and server usage is False
